name: "Bundler Audit Check"
description: "Runs bundle-audit on pull requests with Gemfile.lock changes and fails the workflow if vulnerabilities are found."

inputs:
  ignore-list:
    description: "Space-separated list of CVEs to ignore (e.g., CVE-2023-26141 CVE-2021-41182 CVE-2021-41183)"
    required: false
    default: ""


runs:
  using: "composite"
  steps:
    - name: Run Bundle Audit
      uses: planningcenter/bundle-audit-action@v1
      id: bundle_audit
      with:
        args: ${{ inputs.ignore-list && '--ignore ' + inputs.ignore-list }}

    - name: Fail Workflow if Vulnerabilities Found
      if: ${{ steps.bundle_audit.outputs.has_vulnerabilities == 'true' }}
      run: |
        cat <<EOF | jq -r .
        ${{ steps.bundle_audit.outputs.audit_output }}
        EOF
        exit 1
      shell: bash
